version: '3'
services:
  actix:
    build: ./actix
    ports:
    - "5001:8080"
  express:
    build: ./express
    ports:
    - "5002:3000"
  flask:
    build: ./flask
    ports:
    - "5003:5000"
  gobuffalo:
    build: ./gobuffalo
    ports:
    - "5004:3000"
  rubyrails:
    build: ./rubyrails
    ports:
    - "5005:3000"
  springboot:
    build: ./springboot
    ports:
    - "5006:8080"
  webapi:
    build: ./webapi
    ports:
    - "5007:80"
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
    - actix
    - express
    - flask
    - gobuffalo
    - rubyrails
    - springboot
    - webapi